name: docs
on:
  push:
    branches: [main]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Build Docs
        run: |
          npm ci
          npm run doc:types
      - name: Push
        env:
          MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          git add .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "$MESSAGE"
          git push origin main:docs -f